Repository crazywhalecc/static-php-cli, pull requests merged in 2023-08, with the labels that each got.

#114 add php 8.3 support for phpmicro
  src/SPC/store/SourcePatcher.php
Labels: enhancement, kind/dependency

#115 add hardcoded ini injection on build process
  src/SPC/command/BuildCliCommand.php
  src/SPC/store/SourcePatcher.php
Labels: enhancement, kind/framework

#119 replace symfony console return values
  src/SPC/ConsoleApplication.php
  src/SPC/command/BaseCommand.php
  src/SPC/command/BuildCliCommand.php
  src/SPC/command/BuildLibsCommand.php
  src/SPC/command/DeployCommand.php
  src/SPC/command/DoctorCommand.php
  src/SPC/command/DownloadCommand.php
  src/SPC/command/DumpLicenseCommand.php
  src/SPC/command/ExtractCommand.php
  src/SPC/command/ListExtCommand.php
  src/SPC/command/MicroCombineCommand.php
  src/SPC/command/SortConfigCommand.php
  src/SPC/command/dev/AllExtCommand.php
  src/SPC/command/dev/ExtInfoCommand.php
  src/SPC/command/dev/PhpVerCommand.php
Labels: kind/framework

#120 remove gotop
  src/SPC/doctor/item/MacOSToolCheckList.php
Labels: bug, kind/framework

#122 remove list-ext command, use all-ext and alias to support its function
  src/SPC/ConsoleApplication.php
  src/SPC/command/ListExtCommand.php
  src/SPC/command/dev/AllExtCommand.php
  src/SPC/command/dev/SortConfigCommand.php
Labels: kind/framework

#125 Fix redis-session support
  config/ext.json
  src/SPC/builder/extension/redis.php
Labels: bug, kind/extension

#128 mongodb source.json change from tgz to zip
  config/source.json
Labels: bug, kind/dependency

#131 minor: prevent warning when installing cmake with Homebrew
  src/SPC/doctor/item/MacOSToolCheckList.php
Labels: bug, kind/framework

#133 add swoole pgsql (--enable-swoole-pgsql)
  config/ext.json
  src/SPC/builder/extension/swoole.php
Labels: enhancement, kind/extension

#134 fix: musl detection on non-x86_64
  src/SPC/doctor/item/LinuxMuslCheck.php
Labels: bug, need test, kind/framework

#139 fix linux builder cpp link option
  src/SPC/builder/linux/LinuxBuilder.php
Labels: bug, kind/dependency, os/linux

#142 fix: check of xz
  src/SPC/doctor/item/LinuxToolCheckList.php
Labels: bug, kind/framework

#143 fix: ExceptionHandler:: must not be accessed before initialization
  src/SPC/exception/ExceptionHandler.php
Labels: bug, kind/framework

#147 Fix webp compile to cmake, fix #95
  src/SPC/builder/unix/library/libwebp.php
Labels: bug, kind/dependency, os/linux

#149 Fix curl in musl-gcc bug, fix #88
  src/SPC/builder/unix/library/curl.php
Labels: bug, kind/dependency, os/linux

#154 fix: curl dependency on openssl
  config/lib.json
Labels: bug, kind/dependency

#156 Remove unused source libressl
  config/source.json
Labels: bug, kind/framework
