Repository crazywhalecc/static-php-cli, pull requests merged in 2023-10, with the labels that each got.

#213 fix bugs when building micro and embed at the same time
  src/SPC/builder/linux/LinuxBuilder.php
  src/SPC/builder/macos/MacOSBuilder.php
  src/SPC/store/SourcePatcher.php
Labels: bug, kind/php-src

#220 add SourcePatcher::patchFile
  src/SPC/store/SourcePatcher.php
Labels: enhancement, kind/framework

#221 adjust store classes
  src/SPC/store/FileSystem.php
  src/SPC/store/SourceExtractor.php
Labels: kind/framework

#222 change default download php to 8.2
  src/SPC/command/DownloadCommand.php
Labels: kind/php-src

#223 fix `--with-clean` to make it work
  src/SPC/command/BuildCliCommand.php
  src/SPC/command/BuildCommand.php
Labels: bug, kind/framework

#224 remove redundant LinuxLibraryBase tryBuild
  src/SPC/builder/linux/library/LinuxLibraryBase.php
Labels: kind/framework

#225 adjust linux distro detection
  src/SPC/builder/linux/SystemUtil.php
Labels: kind/framework, os/linux

#227 fix mongodb release file match
  config/source.json
Labels: bug, kind/dependency

#229 fix docker alpine install package redundant link
  bin/spc-alpine-docker
Labels: bug, kind/workflow

#232 add exception handling for incorrect source.json config
  config/source.json
  src/SPC/util/LicenseDumper.php
Labels: bug, kind/framework

#236 fix curl 7.4.0 CoreServices framework build bug for mac
  config/lib.json
  src/SPC/builder/macos/library/curl.php
Labels: bug, kind/dependency, os/macos

#241 Support downloading sources by specified extensions
  src/SPC/command/DownloadCommand.php
  src/SPC/util/DependencyUtil.php
Labels: enhancement, kind/framework

#244 rename --by-extensions to --for-extensions
  README-zh.md
  README.md
  src/SPC/command/DownloadCommand.php
  src/SPC/command/DumpLicenseCommand.php
Labels: kind/framework

#247 fix macOS imagemagick libwebp linking issue
  src/SPC/builder/unix/library/libwebp.php
Labels: bug, os/macos

#250 Fix prompts dependency and box pack path
  box.json
  composer.json
  composer.lock
Labels: bug, kind/framework
