Repository crazywhalecc/static-php-cli, pull requests merged in 2023-09, with the labels that each got.

#164 Add GH Action for tests
  .github/workflows/tests.yml
Labels: enhancement, kind/framework

#166 cs fix
  src/SPC/builder/traits/LibraryTrait.php
  src/SPC/doctor/AsCheckItem.php
  src/SPC/doctor/AsFixItem.php
  src/SPC/doctor/CheckResult.php
  src/SPC/exception/DownloaderException.php
  src/SPC/exception/FileSystemException.php
  src/SPC/exception/InvalidArgumentException.php
  src/SPC/exception/RuntimeException.php
  src/SPC/exception/ValidationException.php
  src/SPC/exception/WrongUsageException.php
  src/SPC/util/CustomExt.php
Labels: kind/framework

#168 add build:libs option --rebuild
  src/SPC/builder/BuilderBase.php
  src/SPC/command/BuildLibsCommand.php
Labels: enhancement, kind/framework

#169 dev:sort-config add `\n` at the end of json
  src/SPC/command/dev/SortConfigCommand.php
Labels: kind/framework

#174 fix Alpine docker install packages #173
  bin/spc-alpine-docker
Labels: bug, kind/workflow

#176 Prevent fatal error when php source files are missing
  src/SPC/command/dev/PhpVerCommand.php
Labels: bug, kind/framework

#167 Rework doctor command
  src/SPC/command/DoctorCommand.php
  src/SPC/doctor/CheckListHandler.php
  tests/SPC/doctor/CheckListHandlerTest.php
Labels: kind/framework

#170 fix libwebp pkgconfig patch, add custom patch argument
  src/SPC/builder/traits/UnixLibraryTrait.php
  src/SPC/builder/unix/library/libwebp.php
  src/globals/defines.php
Labels: bug, kind/dependency

#172 fix ln src and dst for brotli
  src/SPC/builder/unix/library/brotli.php
Labels: bug, kind/dependency

#171 remove redundant libssh2 cmake build target option
  src/SPC/builder/unix/library/libssh2.php
Labels: bug, kind/dependency

#182 Sanity check extensions by inline their test code
  src/SPC/builder/traits/UnixBuilderTrait.php
  src/globals/tests/dom.php
Labels: bug, kind/framework

#186 fix(docker): php82-sodium is required
  bin/spc-alpine-docker
Labels: kind/workflow

#184 Add new GH action to build binary SPC
  .github/workflows/release-build.yml
Labels: enhancement, kind/workflow

#189 add hardcoded-ini option for embed SAPI
  src/SPC/ConsoleApplication.php
  src/SPC/store/SourcePatcher.php
Labels: enhancement, kind/php-src

#201 cs fix and composer update
  composer.lock
  src/SPC/command/BuildCliCommand.php
Labels: kind/framework

#200 Adjust micro's phar patch execution location
  src/SPC/builder/linux/LinuxBuilder.php
  src/SPC/builder/macos/MacOSBuilder.php
Labels: bug, kind/dependency

#210 Remove dead code from `ConsoleApplication` class
  src/SPC/ConsoleApplication.php
Labels: kind/framework

#211 Throw proper exception when PHP source is not available
  src/SPC/builder/BuilderBase.php
  src/SPC/builder/extension/openssl.php
  src/SPC/builder/extension/swow.php
  src/SPC/util/Util.php
Labels: kind/framework
