Repository crazywhalecc/static-php-cli, pull requests merged in 2023-12, with the labels that each got.

#279 upgrade libpq to v16.1
  config/lib.json
  config/source.json
  src/SPC/builder/BuilderBase.php
  src/SPC/builder/extension/mongodb.php
  src/SPC/builder/extension/swoole.php
  src/SPC/builder/unix/library/ldap.php
  src/SPC/builder/unix/library/postgresql.php
  src/globals/test-extensions.php
Labels: bug, kind/dependency

#64 Add support for libargon2
  config/ext.json
  config/lib.json
  config/source.json
  src/SPC/builder/extension/password_argon2.php
  src/SPC/builder/linux/library/libargon2.php
  src/SPC/builder/macos/library/libargon2.php
  src/SPC/builder/unix/library/libargon2.php
  src/globals/test-extensions.php
Labels: enhancement, kind/dependency

#290 Use bulk combination for setup-runtime
  bin/setup-runtime
Labels: kind/workflow

#296 Add uv/libuv support
  config/ext.json
  config/lib.json
  config/source.json
  src/SPC/builder/linux/library/libuv.php
  src/SPC/builder/macos/library/libuv.php
  src/SPC/builder/unix/library/libuv.php
  src/globals/test-extensions.php
Labels: enhancement, kind/extension

#298 Add composer library mode
  bin/spc
  src/globals/defines.php
Labels: enhancement, kind/framework
