Repository crazywhalecc/static-php-cli, pull requests merged in 2023-07, with the labels that each got.

#84 添加pgsql 库
  config/ext.json
  config/lib.json
  config/source.json
  src/SPC/builder/linux/library/postgresql.php
  src/SPC/builder/macos/library/postgresql.php
  src/SPC/builder/unix/library/postgresql.php
  src/SPC/store/SourcePatcher.php
Labels: kind/extension, kind/dependency

#98 add memcache support
  config/ext.json
  config/source.json
  src/SPC/builder/extension/memcache.php
  src/SPC/store/SourcePatcher.php
Labels: enhancement, kind/extension

#102 fix pgsql dependency
  config/ext.json
Labels: bug, kind/dependency, os/linux

#101 fix libpng build bug for linux
  src/SPC/builder/linux/library/libpng.php
Labels: bug, kind/dependency, os/linux

#103 add strip option (fix #97)
  src/SPC/command/BuildCliCommand.php
Labels: bug, kind/framework

#104 fix mbregex without mbstring failed check (fix #96)
  config/ext.json
  src/SPC/builder/extension/mbregex.php
Labels: bug, kind/extension

#105 Enable compile optimization for other libraries
  src/SPC/builder/macos/MacOSBuilder.php
Labels: enhancement, kind/dependency, os/macos

#107 add extract command, add -U option (custom download source)
  src/SPC/ConsoleApplication.php
  src/SPC/builder/BuilderBase.php
  src/SPC/command/DownloadCommand.php
  src/SPC/command/ExtractCommand.php
  src/SPC/command/dev/PhpVerCommand.php
  src/SPC/store/Downloader.php
  src/SPC/store/SourceExtractor.php
Labels: enhancement, kind/framework

#112 Fix mysqlnd dependency #111
  config/ext.json
Labels: bug, kind/extension
