Repository crazywhalecc/static-php-cli, pull requests merged in 2024-07, with the labels that each got.

#492 Merge docs into static-php-cli repo
  .github/pull_request_template.md
  .github/workflows/vitepress-deploy.yml
  .gitignore
  README-zh.md
  README.md
  docs/.vitepress/components/CliGenerator.vue
  docs/.vitepress/components/DependencyUtil.js
  docs/.vitepress/config.ts
  docs/.vitepress/sidebar.en.ts
  docs/.vitepress/sidebar.zh.ts
  docs/.vitepress/theme/index.ts
  docs/en/contributing/index.md
  docs/en/develop/doctor-module.md
  docs/en/develop/index.md
  docs/en/develop/source-module.md
  docs/en/develop/structure.md
  docs/en/develop/system-build-tools.md
  docs/en/faq/index.md
  docs/en/guide/action-build.md
  docs/en/guide/build-on-windows.md
  docs/en/guide/cli-generator.md
  docs/en/guide/env-vars.md
  docs/en/guide/extension-notes.md
  docs/en/guide/extensions.md
  docs/en/guide/index.md
  docs/en/guide/manual-build.md
  docs/en/guide/troubleshooting.md
  docs/en/index.md
  docs/extension-notes.md
  docs/extensions.md
  docs/index.md
  docs/public/CNAME
  docs/zh/contributing/index.md
  docs/zh/develop/doctor-module.md
  docs/zh/develop/index.md
  docs/zh/develop/source-module.md
  docs/zh/develop/structure.md
  docs/zh/develop/system-build-tools.md
  docs/zh/faq/index.md
  docs/zh/guide/action-build.md
  docs/zh/guide/build-on-windows.md
  docs/zh/guide/cli-generator.md
  docs/zh/guide/env-vars.md
  docs/zh/guide/extension-notes.md
  docs/zh/guide/extensions.md
  docs/zh/guide/index.md
  docs/zh/guide/manual-build.md
  docs/zh/guide/troubleshooting.md
  docs/zh/index.md
  package.json
  src/SPC/builder/LibraryBase.php
Labels: documentation

#494 docs: Add php-src modifications & Release SPC enhancement
  .github/workflows/release-build.yml
  .github/workflows/tests.yml
  docs/.vitepress/config.ts
  docs/.vitepress/sidebar.en.ts
  docs/.vitepress/sidebar.zh.ts
  docs/en/develop/php-src-changes.md
  docs/zh/develop/php-src-changes.md
Labels: documentation, kind/workflow, mixed PR

#495 fix: xz download
  config/source.json
Labels: bug, kind/dependency

#499 Fix libyaml patch slashes
  src/SPC/store/SourcePatcher.php
  src/globals/extra/libyaml_yamlConfig.cmake.in
  src/globals/test-extensions.php
Labels: bug, kind/dependency

#500 Fix prefer-stable negative result in ghtar
  src/SPC/store/Downloader.php
  src/globals/test-extensions.php
Labels: bug, kind/framework

#501 Add spx extension support
  .github/workflows/tests.yml
  config/ext.json
  config/source.json
  docs/en/guide/extension-notes.md
  docs/zh/guide/extension-notes.md
  src/SPC/builder/extension/spx.php
  src/globals/test-extensions.php
Labels: enhancement, kind/extension

#506 Fix openssl source
  config/source.json
  src/SPC/ConsoleApplication.php
Labels: bug, kind/dependency

#508 Fix imap and rar build on macOS bug
  src/SPC/builder/extension/imap.php
  src/SPC/builder/extension/rar.php
  src/SPC/builder/macos/library/imap.php
  src/SPC/store/SourcePatcher.php
  src/globals/test-extensions.php
Labels: bug, kind/extension, mixed PR
