Repository crazywhalecc/static-php-cli, pull requests merged in 2024-01, with the labels that each got.

#297 Feature perfect swoole extension config
  bin/setup-runtime
  config/ext.json
  config/lib.json
  config/source.json
  phpstan.neon
  src/SPC/builder/BuilderBase.php
  src/SPC/builder/extension/swoole.php
  src/SPC/builder/extension/swoole_hook_mysql.php
  src/SPC/builder/extension/swoole_hook_pgsql.php
  src/SPC/builder/extension/swoole_hook_sqlite.php
  src/SPC/builder/linux/LinuxBuilder.php
  src/SPC/builder/linux/library/libcares.php
  src/SPC/builder/linux/library/nghttp2.php
  src/SPC/builder/macos/MacOSBuilder.php
  src/SPC/builder/macos/library/libcares.php
  src/SPC/builder/macos/library/nghttp2.php
  src/SPC/builder/unix/library/brotli.php
  src/SPC/builder/unix/library/libcares.php
  src/SPC/builder/unix/library/nghttp2.php
  src/SPC/builder/unix/library/postgresql.php
  src/SPC/store/FileSystem.php
  src/SPC/store/SourcePatcher.php
  src/globals/functions.php
  src/globals/test-extensions.php
  src/globals/tests/swoole.php
Labels: kind/extension, need test

#304 fix libxml2 with icu finding issue
  config/lib.json
  src/SPC/builder/linux/library/libxml2.php
  src/SPC/builder/macos/library/libxml2.php
  src/globals/test-extensions.php
Labels: bug, kind/dependency

#308 fix #307 uv 和 swoole 同时启用的时候会提示 uv 找不到
  .php-cs-fixer.php
  composer.lock
  config/ext.json
  src/SPC/builder/unix/library/brotli.php
  src/globals/test-extensions.php
Labels: bug, kind/extension

#314 add deepin support for doctor
  src/SPC/builder/linux/SystemUtil.php
  src/SPC/doctor/item/LinuxToolCheckList.php
  src/SPC/doctor/item/OSCheckList.php
Labels: enhancement, os/linux

#313 fix --from-zip not working bug
  src/SPC/command/DownloadCommand.php
Labels: bug, kind/framework

#315 Adjust function to protected
  src/SPC/builder/BuilderBase.php
  src/SPC/builder/freebsd/BSDBuilder.php
  src/SPC/builder/linux/LinuxBuilder.php
  src/SPC/builder/macos/MacOSBuilder.php
  src/SPC/builder/traits/UnixBuilderTrait.php
Labels: kind/framework

#321 Add more tests
  src/SPC/store/FileSystem.php
  src/globals/test-extensions.php
  tests/SPC/globals/GlobalFunctionsTest.php
  tests/SPC/store/ConfigTest.php
  tests/SPC/util/ConfigValidatorTest.php
  tests/SPC/util/LicenseDumperTest.php
Labels: kind/framework
