Repository crazywhalecc/static-php-cli, pull requests merged in 2024-12, with the labels that each got.

#561 Add missing step to docs
  docs/en/guide/build-on-windows.md
Labels: documentation

#570 Fix pgsql linux builds with PHP 8.4
  src/SPC/builder/extension/pgsql.php
Labels: bug, kind/extension, os/linux

#572 Fix pgsql missing symbol again
  src/SPC/builder/extension/pgsql.php
Labels: bug, kind/extension

#256 Add extension rdkafka support
  config/ext.json
  config/lib.json
  config/source.json
  src/SPC/builder/extension/rdkafka.php
  src/SPC/builder/linux/library/librdkafka.php
  src/SPC/builder/macos/library/librdkafka.php
  src/SPC/builder/unix/library/librdkafka.php
  src/globals/test-extensions.php
Labels: enhancement, kind/extension

#574 Update SQLite to 3.45
  config/source.json
Labels: enhancement, kind/dependency

#575 Add libaom, libde265, libheif support, for imagick AVIF format support
  config/ext.json
  config/lib.json
  config/source.json
  src/SPC/builder/linux/library/libaom.php
  src/SPC/builder/linux/library/libde265.php
  src/SPC/builder/linux/library/libheif.php
  src/SPC/builder/macos/library/libaom.php
  src/SPC/builder/macos/library/libde265.php
  src/SPC/builder/macos/library/libheif.php
  src/SPC/builder/unix/library/libaom.php
  src/SPC/builder/unix/library/libde265.php
  src/SPC/builder/unix/library/libheif.php
  src/globals/ext-tests/imagick.php
  src/globals/test-extensions.php
Labels: enhancement, kind/dependency

#579 Add aom patch for alpine linux
  src/SPC/store/SourcePatcher.php
  src/globals/patch/libaom_posix_implict.patch
Labels: bug, kind/dependency

#581 Fix openssl missing cert bug for Linux & macOS
  src/SPC/builder/linux/library/openssl.php
  src/SPC/builder/macos/library/openssl.php
  src/globals/ext-tests/openssl.php
  src/globals/test-extensions.php
Labels: bug, kind/dependency
