Repository crazywhalecc/static-php-cli, pull requests merged in 2024-10, with the labels that each got.

#551 Update docs vue components
  docs/.vitepress/components/CliGenerator.vue
  docs/.vitepress/components/SearchTable.vue
  docs/en/guide/cli-generator.md
  docs/en/guide/extensions.md
  docs/zh/guide/cli-generator.md
  docs/zh/guide/extensions.md
Labels: documentation

#511 Add option to manually specify config file path
  docs/en/guide/build-on-windows.md
  docs/en/guide/manual-build.md
  docs/zh/guide/manual-build.md
  src/SPC/builder/linux/LinuxBuilder.php
  src/SPC/builder/macos/MacOSBuilder.php
  src/SPC/command/BuildCliCommand.php
Labels: enhancement, kind/framework

#553 feat: better default for the php.ini path
  docs/en/faq/index.md
  docs/en/guide/build-on-windows.md
  docs/en/guide/manual-build.md
  docs/zh/faq/index.md
  docs/zh/guide/build-on-windows.md
  docs/zh/guide/manual-build.md
  src/SPC/ConsoleApplication.php
  src/SPC/builder/freebsd/BSDBuilder.php
  src/SPC/builder/linux/LinuxBuilder.php
  src/SPC/builder/macos/MacOSBuilder.php
  src/SPC/builder/windows/WindowsBuilder.php
  src/SPC/command/BuildCliCommand.php
Labels: kind/php-and-sapi
