Repository crazywhalecc/static-php-cli, pull requests merged in 2024-05, with the labels that each got.

#420 Windows build GitHub Action
  .github/workflows/build-windows-x86_64.yml
Labels: enhancement, kind/workflow, os/windows

#437 Add linux env var: SPC_NO_MUSL_PATH
  src/SPC/util/GlobalEnvManager.php
Labels: enhancement, kind/framework, os/linux

#438 Fix xz build on macOS and Linux
  src/SPC/builder/macos/library/xz.php
  src/SPC/builder/unix/library/xz.php
  src/globals/test-extensions.php
Labels: bug, kind/dependency

#439 Fix ncurses 6.5 build
  config/source.json
  src/SPC/builder/unix/library/ncurses.php
  src/globals/test-extensions.php
Labels: bug, kind/dependency

#440 Fix micro upx compress bug
  src/SPC/builder/linux/LinuxBuilder.php
  src/SPC/command/BuildCliCommand.php
  src/globals/extra/micro-triple-Makefile.frag
Labels: bug, os/linux, kind/php-src

#441 Fix dependency util suggest calculate bug
  src/SPC/util/DependencyUtil.php
Labels: bug, kind/framework

#444 Add extension parallel support
  .github/workflows/tests.yml
  config/ext.json
  config/lib.json
  config/source.json
  src/SPC/builder/extension/parallel.php
  src/SPC/builder/windows/library/pthreads4w.php
  src/globals/test-extensions.php
  src/globals/tests/parallel.php
Labels: enhancement, kind/extension

#450 Fix php74 upx bug
  .github/workflows/tests.yml
  composer.json
  composer.lock
  config/ext.json
  src/SPC/ConsoleApplication.php
  src/SPC/builder/freebsd/BSDBuilder.php
  src/SPC/builder/linux/LinuxBuilder.php
  src/SPC/command/BaseCommand.php
  src/SPC/command/BuildCliCommand.php
  src/SPC/command/BuildLibsCommand.php
  src/SPC/command/DumpLicenseCommand.php
  src/SPC/util/GlobalEnvManager.php
  src/SPC/util/LicenseDumper.php
  src/SPC/util/Patcher.php
  src/SPC/util/UnixShell.php
  src/SPC/util/WindowsCmd.php
  src/globals/functions.php
Labels: bug, kind/framework

#451 Put extension and library compatibility checks before compilation
  src/SPC/builder/BuilderBase.php
  src/SPC/builder/Extension.php
  src/SPC/builder/LibraryBase.php
  src/SPC/builder/extension/imap.php
  src/SPC/builder/extension/opcache.php
  src/SPC/builder/extension/parallel.php
  src/SPC/builder/extension/swoole_hook_pgsql.php
  src/SPC/builder/extension/swoole_hook_sqlite.php
  src/SPC/builder/freebsd/BSDBuilder.php
  src/SPC/builder/unix/UnixBuilderBase.php
  src/SPC/builder/windows/WindowsBuilder.php
  src/SPC/command/BuildCliCommand.php
  src/SPC/command/BuildLibsCommand.php
Labels: enhancement, kind/framework

#452 Add compression for spc.phar and spc.exe
  box.json
Labels: enhancement, kind/framework

#457 Add comomand: `switch-php-version`
  README-zh.md
  README.md
  src/SPC/command/SwitchPhpVersionCommand.php
Labels: enhancement, kind/framework

#458 Add extension version and env check method
  src/SPC/ConsoleApplication.php
  src/SPC/builder/extension/opcache.php
  src/SPC/builder/extension/protobuf.php
  src/SPC/builder/extension/swow.php
Labels: enhancement, kind/framework

#459 Remove dll before sanity check
  src/SPC/builder/windows/WindowsBuilder.php
Labels: kind/framework, os/windows

#462 Add gen-ext-docs command
  .github/workflows/update-docs-config.yml
  config/ext.json
  src/SPC/ConsoleApplication.php
  src/SPC/command/dev/GenerateExtDocCommand.php
Labels: enhancement, kind/framework

#463 Add libxml extension wrapper for composer compatibility
  config/ext.json
  src/globals/test-extensions.php
Labels: enhancement, kind/extension

#467 Fix macOS --no-strip opposite bug
  src/SPC/builder/macos/MacOSBuilder.php
Labels: bug, kind/framework, os/macos
