Repository crazywhalecc/static-php-cli, pull requests merged in 2025-03, with the labels that each got.

#599 Add command to dump required PHP extensions based on vendor/composer/…
  README.md
  docs/en/guide/manual-build.md
  docs/zh/guide/manual-build.md
  src/SPC/ConsoleApplication.php
  src/SPC/command/BaseCommand.php
  src/SPC/command/DumpExtensionsCommand.php
Labels: new feature, kind/framework

#616 Remove deprecated args for PHP 8.4
  config/ext.json
  src/SPC/builder/extension/memcached.php
  src/SPC/builder/extension/openssl.php
  src/SPC/builder/extension/zlib.php
  src/globals/test-extensions.php
Labels: bug, kind/php-and-sapi

#618 Add php and lib-base as special libraries to add dependencies to the root node
  config/lib.json
  src/SPC/builder/LibraryBase.php
  src/SPC/builder/unix/UnixBuilderBase.php
  src/SPC/builder/windows/WindowsBuilder.php
  src/SPC/command/BaseCommand.php
  src/SPC/command/BuildCliCommand.php
  src/SPC/command/BuildLibsCommand.php
  src/SPC/command/DownloadCommand.php
  src/SPC/command/dev/SortConfigCommand.php
  src/SPC/store/Config.php
  src/SPC/util/ConfigValidator.php
  src/SPC/util/DependencyUtil.php
  src/SPC/util/LicenseDumper.php
  src/globals/functions.php
  tests/SPC/builder/ExtensionTest.php
  tests/SPC/builder/unix/UnixSystemUtilTest.php
  tests/SPC/util/DependencyUtilTest.php
  tests/SPC/util/LicenseDumperTest.php
Labels: new feature, kind/framework

#621 update php default to 8.4
  README.md
  composer.json
  docs/en/guide/manual-build.md
  src/SPC/command/DownloadCommand.php
Labels: bug

#622 bring back pr for libacl
  .github/workflows/build-unix.yml
  bin/spc-gnu-docker
  config/env.ini
  config/lib.json
  config/source.json
  src/SPC/builder/Extension.php
  src/SPC/builder/LibraryBase.php
  src/SPC/builder/linux/LinuxBuilder.php
  src/SPC/builder/linux/library/attr.php
  src/SPC/builder/linux/library/libacl.php
  src/SPC/builder/linux/library/libpng.php
  src/SPC/builder/unix/library/attr.php
  src/SPC/builder/unix/library/curl.php
  src/SPC/builder/unix/library/libacl.php
  src/SPC/builder/unix/library/pkgconfig.php
  src/SPC/command/BuildCliCommand.php
  src/SPC/doctor/item/LinuxToolCheckList.php
  src/SPC/store/SourcePatcher.php
  src/SPC/util/GlobalEnvManager.php
  src/globals/patch/attr_alpine_gethostname.patch
Labels: kind/php-and-sapi, mixed PR

#627 Update musl-wrapper version to 1.2.5 and apply CVE patch
  src/SPC/doctor/item/LinuxMuslCheck.php
  src/globals/patch/musl-1.2.5_CVE-2025-26519_0001.patch
  src/globals/patch/musl-1.2.5_CVE-2025-26519_0002.patch
  src/globals/test-extensions.php
Labels: bug, kind/dependency

#629 Update docs for FFI and dynamic loading extensions
  docs/en/faq/index.md
  docs/en/guide/extension-notes.md
  docs/zh/faq/index.md
  docs/zh/guide/extension-notes.md
Labels: documentation

#628 fix embed SAPI php-config prefix
  src/SPC/builder/linux/LinuxBuilder.php
Labels: bug, kind/php-and-sapi

#636 Update automake on gnu docker to fix attr build bug
  bin/build-static-frankenphp
  bin/spc-gnu-docker
Labels: bug, kind/dependency

#635 don't require libacl and attr - use --with-libs='libacl' if you build…
  config/lib.json
  src/SPC/builder/unix/library/attr.php
  src/SPC/command/BuildCliCommand.php
Labels: bug, kind/dependency

#641 Fix imagick patch newer than 30800
  src/SPC/store/SourcePatcher.php
  src/globals/patch/imagick_php84_before_30800.patch
  src/globals/test-extensions.php
Labels: bug, kind/extension

#634 Fix gettext on locale bug
  bin/build-static-frankenphp
  bin/spc-alpine-docker
  bin/spc-gnu-docker
  config/ext.json
  src/SPC/builder/unix/library/attr.php
  src/SPC/builder/unix/library/libacl.php
  src/SPC/doctor/item/LinuxToolCheckList.php
  src/globals/ext-tests/gettext.php
  src/globals/test-extensions.php
Labels: bug, kind/extension

#646 fix libxslt license file path
  config/source.json
Labels: fixed

#642 Remove SPC_NO_MUSL_PATH, remove --libc, use SPC_LIBC instead
  .github/workflows/tests.yml
  bin/build-static-frankenphp
  bin/spc-gnu-docker
  config/env.ini
  docs/en/faq/index.md
  docs/en/guide/build-with-glibc.md
  docs/zh/faq/index.md
  docs/zh/guide/build-with-glibc.md
  src/SPC/ConsoleApplication.php
  src/SPC/builder/linux/LinuxBuilder.php
  src/SPC/builder/linux/SystemUtil.php
  src/SPC/builder/linux/library/icu.php
  src/SPC/builder/linux/library/libffi.php
  src/SPC/builder/linux/library/libpng.php
  src/SPC/builder/linux/library/openssl.php
  src/SPC/builder/macos/MacOSBuilder.php
  src/SPC/builder/macos/library/libffi.php
  src/SPC/builder/macos/library/openssl.php
  src/SPC/builder/unix/UnixBuilderBase.php
  src/SPC/builder/unix/library/curl.php
  src/SPC/builder/unix/library/imagemagick.php
  src/SPC/builder/unix/library/ldap.php
  src/SPC/builder/unix/library/pkgconfig.php
  src/SPC/builder/unix/library/postgresql.php
  src/SPC/command/BuildCommand.php
  src/SPC/command/BuildPHPCommand.php
  src/SPC/doctor/item/LinuxMuslCheck.php
  src/SPC/doctor/item/MacOSToolCheckList.php
  src/SPC/store/SourcePatcher.php
  src/SPC/util/GlobalEnvManager.php
  src/globals/defines.php
  src/globals/internal-env.php
Labels: kind/framework

#649 Fix libavif build on VS2019 syntax error
  src/SPC/builder/windows/library/libavif.php
  src/globals/test-extensions.php
Labels: bug, kind/dependency, os/windows

#650 Fix windows setup-runtime php download link
  bin/setup-runtime.ps1
Labels: os/windows

#653 Add conflict message when building protobuf and grpc
  src/SPC/builder/extension/protobuf.php
Labels: bug, kind/extension

#651 Add sodium extension support for Windows
  config/ext.json
  config/lib.json
  src/SPC/builder/windows/library/libsodium.php
  src/globals/test-extensions.php
Labels: new feature, kind/extension, os/windows

#652 Add missing ext source when downloading pre-built grpc
  src/SPC/builder/extension/grpc.php
  src/SPC/builder/unix/library/grpc.php
  src/globals/test-extensions.php
Labels: bug, kind/framework

#658 Build freetype using CMake instead
  src/SPC/builder/unix/library/freetype.php
  src/globals/test-extensions.php
Labels: bug, kind/dependency

#657 Fix/ffi env
  src/SPC/builder/linux/library/libffi.php
Labels: bug, kind/dependency

#660 Fix windows curl build >= 8.3
  config/lib.json
  src/SPC/builder/windows/library/curl.php
  src/globals/test-extensions.php
Labels: bug, os/windows

#671 fix phpize using wrong paths
  src/SPC/builder/linux/LinuxBuilder.php
  src/SPC/builder/macos/MacOSBuilder.php
Labels: bug, kind/php-and-sapi

#663 Add mimalloc support for macOS and Linux
  config/lib.json
  config/source.json
  docs/en/guide/extension-notes.md
  docs/zh/guide/extension-notes.md
  src/SPC/builder/linux/LinuxBuilder.php
  src/SPC/builder/linux/library/mimalloc.php
  src/SPC/builder/macos/MacOSBuilder.php
  src/SPC/builder/macos/library/mimalloc.php
  src/SPC/builder/unix/library/mimalloc.php
  src/SPC/store/Downloader.php
  src/SPC/util/SPCConfigUtil.php
  src/globals/test-extensions.php
Labels: new feature, kind/dependency

#674 Fix windows ssl bug for curl
  config/lib.json
  src/SPC/ConsoleApplication.php
  src/SPC/builder/windows/library/curl.php
  src/globals/ext-tests/curl.php
  src/globals/test-extensions.php
Labels: bug, kind/dependency, os/windows

#675 Fix windows micro logo changer bug (illegal realpath)
  src/SPC/builder/windows/WindowsBuilder.php
Labels: bug, kind/php-and-sapi, os/windows

#661 enable PDO_ODBC and ODBC extension statically
  config/ext.json
  src/SPC/builder/extension/odbc.php
  src/SPC/builder/extension/pdo_odbc.php
  src/globals/test-extensions.php
Labels: new feature, kind/extension

#665 Add pgsql extension for Windows <#664>
  config/ext.json
  config/lib.json
  config/source.json
  src/SPC/builder/extension/pdo_pgsql.php
  src/SPC/builder/extension/pgsql.php
  src/SPC/builder/windows/library/postgresql_win.php
  src/globals/test-extensions.php
Labels: new feature, kind/extension, os/windows

#685 Downloader enhancement
  .github/workflows/build-unix.yml
  .github/workflows/tests.yml
  bin/spc-alpine-docker
  bin/spc-gnu-docker
  config/pre-built.json
  src/SPC/builder/LibraryBase.php
  src/SPC/builder/linux/SystemUtil.php
  src/SPC/command/DeleteDownloadCommand.php
  src/SPC/command/DownloadCommand.php
  src/SPC/command/dev/PackLibCommand.php
  src/SPC/store/Config.php
  src/SPC/store/Downloader.php
  src/SPC/store/SourceManager.php
  src/SPC/store/source/CustomSourceBase.php
  src/SPC/store/source/PhpSource.php
  src/SPC/store/source/PostgreSQLSource.php
  src/globals/defines.php
  src/globals/test-extensions.php
Labels: kind/framework

#677 Dynamic extension build support for macOS and glibc Linux
  bin/spc-alpine-docker
  bin/spc-gnu-docker
  config/env.ini
  config/ext.json
  config/lib.json
  config/source.json
  src/SPC/builder/BuilderBase.php
  src/SPC/builder/Extension.php
  src/SPC/builder/extension/amqp.php
  src/SPC/builder/extension/dba.php
  src/SPC/builder/extension/enchant.php
  src/SPC/builder/extension/event.php
  src/SPC/builder/extension/ffi.php
  src/SPC/builder/extension/gd.php
  src/SPC/builder/extension/glfw.php
  src/SPC/builder/extension/grpc.php
  src/SPC/builder/extension/imagick.php
  src/SPC/builder/extension/imap.php
  src/SPC/builder/extension/memcache.php
  src/SPC/builder/extension/memcached.php
  src/SPC/builder/extension/mongodb.php
  src/SPC/builder/extension/odbc.php
  src/SPC/builder/extension/opcache.php
  src/SPC/builder/extension/openssl.php
  src/SPC/builder/extension/pdo_odbc.php
  src/SPC/builder/extension/pgsql.php
  src/SPC/builder/extension/redis.php
  src/SPC/builder/extension/snappy.php
  src/SPC/builder/extension/spx.php
  src/SPC/builder/extension/swoole.php
  src/SPC/builder/extension/swoole_hook_mysql.php
  src/SPC/builder/extension/swoole_hook_pgsql.php
  src/SPC/builder/extension/swoole_hook_sqlite.php
  src/SPC/builder/extension/xdebug.php
  src/SPC/builder/extension/xlswriter.php
  src/SPC/builder/extension/xml.php
  src/SPC/builder/extension/yac.php
  src/SPC/builder/extension/zlib.php
  src/SPC/builder/extension/zstd.php
  src/SPC/builder/freebsd/BSDBuilder.php
  src/SPC/builder/linux/LinuxBuilder.php
  src/SPC/builder/linux/library/xdebug.php
  src/SPC/builder/macos/MacOSBuilder.php
  src/SPC/builder/unix/UnixBuilderBase.php
  src/SPC/builder/unix/library/libcares.php
  src/SPC/builder/unix/library/xdebug.php
  src/SPC/builder/windows/WindowsBuilder.php
  src/SPC/command/BaseCommand.php
  src/SPC/command/BuildPHPCommand.php
  src/SPC/command/SPCConfigCommand.php
  src/SPC/command/dev/ExtVerCommand.php
  src/SPC/store/Config.php
  src/SPC/store/Downloader.php
  src/SPC/store/SourcePatcher.php
  src/SPC/util/DynamicExt.php
  src/SPC/util/GlobalEnvManager.php
  src/SPC/util/SPCConfigUtil.php
  tests/SPC/builder/BuilderTest.php
Labels: new feature, kind/framework

#681 Remove openmp support for imagemagick
  config/ext.json
  config/lib.json
  docs/en/guide/extension-notes.md
  docs/zh/guide/extension-notes.md
  src/SPC/builder/extension/imagick.php
  src/SPC/builder/unix/library/imagemagick.php
  src/SPC/store/FileSystem.php
  src/SPC/util/SPCConfigUtil.php
  src/globals/test-extensions.php
Labels: bug, kind/dependency, os/linux

#689 Add extract source only mode for SourceManager
  src/SPC/builder/BuilderBase.php
  src/SPC/builder/LibraryBase.php
  src/SPC/command/ExtractCommand.php
  src/SPC/store/SourceManager.php
Labels: bug, kind/framework
