Repository crazywhalecc/static-php-cli, pull requests merged in 2025-04, with the labels that each got.

#696 don't set EXTENSION_DIR by default
  config/env.ini
Labels: bug, kind/php-and-sapi

#700 Add more PHPUnit tests
  tests/SPC/GlobalDefinesTest.php
  tests/SPC/GlobalFunctionsTest.php
  tests/SPC/util/ConfigValidatorTest.php
  tests/SPC/util/DependencyUtilTest.php
  tests/SPC/util/LicenseDumperTest.php
  tests/SPC/util/SPCConfigUtilTest.php
Labels: kind/framework

#673 add xdebug dynamic extension
  .github/workflows/tests.yml
  bin/spc-alpine-docker
  bin/spc-gnu-docker
  config/env.ini
  config/ext.json
  config/lib.json
  config/source.json
  docs/en/guide/extension-notes.md
  docs/en/guide/manual-build.md
  docs/zh/guide/extension-notes.md
  docs/zh/guide/manual-build.md
  src/SPC/builder/BuilderBase.php
  src/SPC/builder/Extension.php
  src/SPC/builder/extension/amqp.php
  src/SPC/builder/extension/dba.php
  src/SPC/builder/extension/enchant.php
  src/SPC/builder/extension/event.php
  src/SPC/builder/extension/ffi.php
  src/SPC/builder/extension/gd.php
  src/SPC/builder/extension/glfw.php
  src/SPC/builder/extension/grpc.php
  src/SPC/builder/extension/imagick.php
  src/SPC/builder/extension/imap.php
  src/SPC/builder/extension/memcache.php
  src/SPC/builder/extension/memcached.php
  src/SPC/builder/extension/mongodb.php
  src/SPC/builder/extension/odbc.php
  src/SPC/builder/extension/opcache.php
  src/SPC/builder/extension/openssl.php
  src/SPC/builder/extension/pdo_odbc.php
  src/SPC/builder/extension/pgsql.php
  src/SPC/builder/extension/redis.php
  src/SPC/builder/extension/snappy.php
  src/SPC/builder/extension/spx.php
  src/SPC/builder/extension/swoole.php
  src/SPC/builder/extension/swoole_hook_mysql.php
  src/SPC/builder/extension/swoole_hook_pgsql.php
  src/SPC/builder/extension/swoole_hook_sqlite.php
  src/SPC/builder/extension/xdebug.php
  src/SPC/builder/extension/xlswriter.php
  src/SPC/builder/extension/xml.php
  src/SPC/builder/extension/yac.php
  src/SPC/builder/extension/zlib.php
  src/SPC/builder/extension/zstd.php
  src/SPC/builder/freebsd/BSDBuilder.php
  src/SPC/builder/linux/LinuxBuilder.php
  src/SPC/builder/macos/MacOSBuilder.php
  src/SPC/builder/unix/UnixBuilderBase.php
  src/SPC/builder/unix/library/libcares.php
  src/SPC/builder/windows/WindowsBuilder.php
  src/SPC/command/BaseCommand.php
  src/SPC/command/BuildPHPCommand.php
  src/SPC/command/SPCConfigCommand.php
  src/SPC/command/dev/ExtVerCommand.php
  src/SPC/store/Config.php
  src/SPC/store/SourcePatcher.php
  src/SPC/util/GlobalEnvManager.php
  src/SPC/util/SPCConfigUtil.php
  src/globals/test-extensions.php
  tests/SPC/builder/BuilderTest.php
Labels: new feature, need test, mixed PR

#701 add mirror sources to savannah downloads
  config/source.json
Labels: bug, kind/dependency

#694 better matching pattern just in case we forget x)
  config/source.json
Labels: bug

#703 Add extension ev support
  config/ext.json
  config/pkg.json
  config/source.json
  src/SPC/builder/extension/ev.php
  src/globals/test-extensions.php
Labels: new feature, kind/extension

#698 Allow CI build to be called by other worklows
  .github/workflows/build-unix.yml
Labels: new feature, kind/workflow

#705 Fix postgresql macOS 15.4 build bug
  src/SPC/builder/unix/library/postgresql.php
  src/globals/test-extensions.php
Labels: bug, kind/dependency

#710 Fix pack lib command with wrong compression
  src/SPC/command/dev/PackLibCommand.php
Labels: bug, kind/framework

#711 Fix ghrel download link, use API directly
  src/SPC/store/Downloader.php
Labels: bug, kind/framework

#712 Add xlswriter extension windows support
  config/ext.json
  src/SPC/builder/extension/xlswriter.php
  src/globals/test-extensions.php
Labels: new feature, kind/extension, os/windows

#719 Fix windows xlswriter duplicate md5 symbol bug
  src/SPC/builder/extension/xlswriter.php
  src/SPC/builder/windows/SystemUtil.php
  src/SPC/store/SourcePatcher.php
  src/globals/patch/spc_fix_xlswriter_win32.patch
  src/globals/test-extensions.php
Labels: bug, kind/extension, os/windows
